---
title: "Delitos de Alto Impacto en Bogota"
author: "Andrés Felipe Bedoya Cruz"
date: "2023-01-12"
output:
  word_document: 
      reference_docx: altoimpacto_reference.docx
  html_document: default
---

```{r opciones de cada chunk de código, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE, dpi=300)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Libs, include = FALSE}
source("Scripts/Librerias.R", encoding = "UTF-8")
windowsFonts("Arial" = windowsFont("Calibri"))
```

```{r}
rm(list=ls())
```

```{r con_azure, include = FALSE}
source("Scripts/Conexion_AzureSQL.R", encoding="UTF-8")
```

```{r graficos, include = FALSE}
source("Scripts/plots.R", encoding="UTF-8")
```

## Tamaño de la base

```{r intances, include=FALSE}
cat(sprintf("La base tiene %s instancias", format(nrow(df_2022), big.mark=",")))
```

**La base tiene `r format(nrow(df_2022), big.mark=",")` instancias**

### Días con mas hechos delictivos

```{r delitos_dia, echo=FALSE, fig.width=7, fig.height=3, fig.align="center"}
hechos_dias
```

En rojo se marca el día con más hechos delictivos para el año 2022.

```{python}
print("hola")
```

```{python}
from codigo import database_connection as db
from codigo.database_connection import column_names
```

```{python}

column_names("Delitos")
```
